/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckboxControl: typeof import('./src/components/CheckboxControl.vue')['default']
    CheckBoxControl: typeof import('./src/components/CheckBoxControl.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Label: typeof import('./src/components/Label.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MetronomeControls: typeof import('./src/components/MetronomeControls.vue')['default']
    MetronomeGrid: typeof import('./src/components/MetronomeGrid.vue')['default']
    MetronomeSection: typeof import('./src/components/MetronomeSection.vue')['default']
    MetronomeTempos: typeof import('./src/components/MetronomeTempos.vue')['default']
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectButtonControl: typeof import('./src/components/SelectButtonControl.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    SliderControl: typeof import('./src/components/SliderControl.vue')['default']
    TempoVariables: typeof import('./src/components/TempoVariables.vue')['default']
  }
}
